### ISSUE TITLE
The new divio.com interface doesn't have a sharing link on the stage (and live) server, hence it isn't possible to test it without being logged in (this is needed for testing though)

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#12]
Before there was the sharing token link, eg `https://stage.eu.aldryn.io/?sharing_token=d1d701b6455dc0ce82ad3ac225f38282d8a488f9e439cb1385e35ce0cda9e8e5`

**Comment by viktor-yunenko** [comment]
Hi @kinkerl, is it something that we could restore? This feature is requested by many clients, if anything they would prefer it to be much more visible, not hidden :)

Eg something as a `anonymous access url` button

**Comment by kinkerl** [comment]
@victor-yunenko this feature is still available. we have to activate it for each project individually. i will reach out to you on a private channel to talk about the details and leave this here for future reference.

**Comment by viktor-yunenko** [comment]
Hi @kinkerl, well I definitely need it to be enabled on every existing and future projects :)

Would you be able to help with it?

In general I would qualify that feature as essential - majority of the projects that I'm working on need a way to test the site without being logged in as a django user. And every client wants their new website to be reviewed by their superiors before pushing it live :)

**Comment by macolo** [comment]
Note: It was also suggested to create a non-staff user (i.e. testing@what.digital) and then log in with that user. However that solution is not suitable, because it doesnt show the website stat as anonymous website visitor (no logged-in django user). Therefore we need the functionality described in this ticket.

**Comment by GaretJax** [comment]
The support for sharing URLs is fully implemented in the aldryn-sso addon installed in the Django projects.

The reason we removed the feature from the control panel (i.e. we removed the button to retrieve the link) is because that feature is very specific to each individual project type and implemented only for Django (and only when the aldryn-sso addon is installed). In an effort to make the platform more generic and to support a wider number of tech stacks, we are slowly removing all Django-specific features.

Support for sharing URLs in Django projects has not been removed however, just the generation of the link on the CP. It is still possible to get those links for any project using the aldryn-sso addon.

The links are in the following form: https://{aldryn_url}/?sharing_token={token}, where the `token` is the value of the `SHARING_VIEW_ONLY_SECRET_TOKEN` environment variable.

The control panel sets that value to a random string on project initialization. You can either retrieve it via SSH or override it by setting your own value in the environment variables. I'd suggest the second approach, as it is less cumbersome to retrieve in the future. The argument name (`sharing_token`) can also be overridden by setting the `SHARING_VIEW_ONLY_TOKEN_KEY_NAME` environment variable to your desired value.

(another thing which has always been possible, it to setup a similar access mode for the live environment as well :-) )

**Comment by macolo** [comment]
BTW it's possible that this only works for test, not for live environments.

**Comment by macolo** [comment]
Note: On live environments, additionally `SHARING_VIEW_ONLY_TOKEN_KEY_NAME` needs to be set to `sharing_token` - there is no default set and preview links will fail to bypass the login screen without it.

**Comment by macolo** [comment]
@kinkerl mentioned that he would add this to the documentation in https://github.com/divio/aldryn-sso
