### ISSUE TITLE
improve documentation of caveats and tacit knowledge that are specific to the Divio platform 

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#18]
This is a generic set of issues that at some point could be split into separate tickets, for now they're useful for developer for only start working with divio cloud:

- There's no guide on how divio deployments work or how a project should be adapted to work with it.
- Divio bot quietly rollbacks files, without telling a developer, eg `addons/`. Developers start spending hours to understand why the project works locally but not on the server, until they accidently do a git pull.
- pip-reqs and requirements.in has a set of issues, part of it is documented in #1 . Eg divio bot can start using requirements.txt without asking the user, just because there's a requirements.txt is in the git root. This results in unfortunate UX where divio bots behaviors contradicts the user's intentions.
- django-filer that comes from divio pypi configures S3 storage, and it isn't possible to use filer without this config. Media files just stop silently working, there should be a warning.

**Comment by macolo** [comment]
Some of this might need to be specified better, at least I am unable to understand the following:

- Eg divio bot can start using requirements.txt without asking the user, just because there's a requirements.txt is in the git root. This results in unfortunate UX where divio bots behaviors contradicts the user's intentions.
- django-filer that comes from divio pypi configures S3 storage, and it isn't possible to use filer without this config. Media files just stop silently working, there should be a warning.


For the following point we just had a call with @GaretJax where we covered the full barebone journey from start to end. Maybe someone can document a summary somewhere.
- There's no guide on how divio deployment works or how a project should be adapted to work with it.

**Comment by macolo** [comment]
We have split these concerns into specific issues and will work on those. Therefore closing this.
