### ISSUE TITLE
Divio bot deletes content of .gitignore file

### ISSUE THREAD

**Issue by macolo** [what-digital/divio#53]
After the creation of a new divio project (blank project, no boilerplates selected) Divio bot is removing all of .gitignore file's content. 

Desired behaviour would be that Divio just adds the one line it has to add to the end of the existing file content.

![gitlab com_what-digital_what-work_what-work-reporting_-_commit_b3d2901c010651b78b4210a8568509aeb83459a5](https://user-images.githubusercontent.com/4056979/132345312-e5d7e300-d800-4855-8ee6-d49ed1dd2744.png)

**Comment by macolo** [comment]
cc @kinkerl

**Comment by kinkerl** [comment]
how did you create the project? from scratch or did you import an existing project from an external source?

Ah! I think the .gitignore file in the boilerplate is not empty and is overwriting the one from the base project because of that. https://github.com/divio/blank-boilerplate
we should update the default .gitignore of the base project and remove the .gitignore of the boilerplate.

**Comment by macolo** [comment]
@GaretJax btw disabling "write access" in gitlab / github is not a feasible workaround because of https://github.com/what-digital/divio/issues/45

**Comment by macolo** [comment]
update from the Divio team:
> We changed some internal logic so the .gitignore file is not longer required and it got removed.
We have a change in the pipeline so webhooks triggers will not push any changes back and will just "blindly" accept the changes from the origin. This should solve the force push issue.
